services:
  ffc-techspike-customer-registry-data-consumer:
    build:
      context: .
      target: production
    image: ffc-techspike-customer-registry-data-consumer
    container_name: ffc-techspike-customer-registry-data-consumer
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-techspike-customer-registry-data-consumer-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      CUSTOMERREGISTRYREQUEST_QUEUE_ADDRESS: ${CUSTOMERREGISTRYREQUEST_QUEUE_ADDRESS:-ffc-techspike-customer-registry-request}${MESSAGE_QUEUE_SUFFIX}
      CUSTOMERREGISTRYALERTREQUEST_QUEUE_ADDRESS: ${CUSTOMERREGISTRYALERTREQUEST_QUEUE_ADDRESS:-ffc-techspike-customer-registry-alert}${MESSAGE_QUEUE_SUFFIX}
      CUSTOMERREGISTRYEVENTREQUEST_QUEUE_ADDRESS: ${CUSTOMERREGISTRYREQUEST_QUEUE_ADDRESS:-ffc-techspike-customer-registry-event}${MESSAGE_QUEUE_SUFFIX}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      COSMOS_ENDPOINT: ${COSMOS_ENDPOINT}
      COSMOS_KEY: ${COSMOS_KEY}
      COSMOS_DATABASE: ${COSMOS_DATABASE}
      COSMOS_CONTAINER: ${COSMOS_CONTAINER}