{{- include "ffc-helm-library.deployment" (list . "ffc-techspike-customer-registry-data-consumer.deployment") -}}
{{- define "ffc-techspike-customer-registry-data-consumer.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-techspike-customer-registry-data-consumer.container") }}
{{- end -}}
