environment: development
name: ffc-techspike-customer-registry-data-consumer
namespace: ffc-techspike
workstream: ffc-techspike
image: ffc-techspike-customer-registry-data-consumer

labels: {}

aadPodIdentity: true

appInsights:
  key:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-techspike-customer-registry-data-consumer-config-map

containerSecret:
  name: ffc-techspike-customer-registry-data-consumer-container-secret
  type: Opaque

deployment:
  cpuThreshold: 40
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 1
  priorityClassName: default
  restartPolicy: Always
  replicas: 1

container:
  customerRegistryRequestQueueAddress: ffc-techspike-customer-registry-request
  messageQueueHost: namespace.servicebus.windows.net
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
